CREATE DATABASE lmsbase;

USE  lmsbase;

CREATE TABLE questions(
    qid INT(250) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    question VARCHAR(250) NOT NULL,
    choice1 VARCHAR(250),
    choice2 VARCHAR(250),
    choice3 VARCHAR(250),
    choice4 VARCHAR(250),
    answer VARCHAR(250) NOT NULL);

CREATE TABLE users(
    uid INT(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    userName VARCHAR(128) NOT NULL,
    userPwd VARCHAR(128) NOT NULL,
    userJob VARCHAR(128) NOT NULL);

